layout_spectrum: 1
typography_spectrum: 0.2043011
color:
  saturation: 1
  lightness: 0.3691756
  brandStrength: 0
  rhythmicContrast: 0.9712167
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Tokyo
